### ISSUE TITLE
Improve reports

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/performance_test_rt_cfg#1]
Here are some ideas to improve the reports:
- [x] Use a better color combination. Some colors are hard to see.
- [x] Add support to pass the set report title
    - https://gitlab.com/ApexAI/performance_test/-/merge_requests/284
- [ ] Use different marker shapes. Color blinds should be able to distinguish different experiments.
    - https://gitlab.com/ApexAI/performance_test/-/issues/140
- [x] Add table showing a summary and the lost messages
- [x] Add legend explaining what is SSTE, STE, etc
- [ ] [Support configurable time units in peformance_report metrics
](https://gitlab.com/ApexAI/performance_test/-/issues/137)
- [ ] [Add test case support to performance_report report verb](https://gitlab.com/ApexAI/performance_test/-/issues/141)

**Comment by carlossvg** [comment]
FYI @flynneva

**Comment by carlossvg** [comment]
@flynneva Where can I find some info to customize the markers and other plot options?

**Comment by flynneva** [comment]
@carlossvg sorry just seeing this....though I think we chatted about this offline.  I think we made a follow up issue on [the performanc_test repo here](https://gitlab.com/ApexAI/performance_test/-/issues/140)

**Comment by carlossvg** [comment]
TODO: check the recently added markdown generated report in https://gitlab.com/ApexAI/performance_test/-/merge_requests/302

**Comment by flynneva** [comment]
@carlossvg i just added a similar feature to the reference system as well if you want to check that out

**Comment by carlossvg** [comment]
Closing this issue since the repo is deprecated in favor of https://github.com/ros-realtime/ros_realtime_benchmarks_config
